---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: openshift-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ldap-group-syncer
rules:
  - apiGroups:
      - ''
      - user.openshift.io
    resources:
      - groups
    verbs:
      - get
      - list
      - create
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ldap-group-syncer
subjects:
  - kind: ServiceAccount
    name: ldap-group-syncer              
    namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ldap-group-syncer                
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync
data:
  whitelist.txt: |
    CN=ocp_admins,CN=Users,DC=acme,DC=local # Edit for your site
    CN=ocp_users,CN=Users,DC=acme,DC=local # Edit for your site
  sync.yaml: |
    kind: LDAPSyncConfig
    apiVersion: v1
    url: ldaps://ados.acme.local:636 # Edit for your site
    insecure: false
    # The CA cert will be mounted into the sync CronJob pod from ca-config-map
    ca: /etc/ldap-ca/ca.crt
    bindDN: "CN=ocp_ldap,CN=Users,DC=acme,DC=local" # Edit for your site
    bindPassword:
      file: "/etc/secrets/bindPassword"
    augmentedActiveDirectory:
      groupsQuery:
        # baseDN and scope are ignored when using "memberOf:1.2.840.113556.1.4.1941:" 
        # baseDN: "CN=Users,DC=acme,DC=local" # Edit for your site
        # scope: sub
        derefAliases: never
        pageSize: 0
      groupUIDAttribute: dn 
      groupNameAttributes: [ cn ] 
      usersQuery:
        baseDN: "CN=Users,DC=acme,DC=local" # Edit for your site
        scope: sub
        derefAliases: never
        filter: (objectclass=person)
        pageSize: 0
      # Use either "sAMAccountName" or "mail", it should match the OAuth resource
      userNameAttributes: [ sAMAccountName ]
      # For group nesting, use "memberOf:1.2.840.113556.1.4.1941:" instead of "memberOf"
      groupMembershipAttributes: [ "memberOf:1.2.840.113556.1.4.1941:" ]
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: ldap-group-syncer
  namespace: openshift-config
spec:                                                                                
  schedule: "*/30 * * * *"                                                           
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 1800                                                  
      template:
        spec:
          containers:
            - name: ldap-group-sync
              image: "registry.redhat.io/openshift4/ose-cli:latest"
              securityContext:
                allowPrivilegeEscalation: false
                seccompProfile:
                   type: RuntimeDefault
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true              
              command:
                - "/bin/bash"
                - "-c"
                - "oc adm groups sync --sync-config=/etc/config/sync.yaml --whitelist=/etc/config/whitelist.txt --confirm" 
              volumeMounts:
                - mountPath: "/etc/config"
                  name: "ldap-sync-volume"
                - mountPath: "/etc/secrets"
                  name: "ldap-bind-password"
                - mountPath: "/etc/ldap-ca"
                  name: "ldap-ca"
          volumes:
            - name: "ldap-sync-volume"
              configMap:
                name: "ldap-group-syncer"
            - name: "ldap-bind-password"
              secret:
                secretName: "ldap-secret"                                            
            - name: "ldap-ca"
              configMap:
                name: "ca-config-map"                                                
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "ldap-group-syncer"
