apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - ldap:
        attributes:
          email:
            - mail
          id:
            - sAMAccountName
          name:
            - cn
          preferredUsername:
            - sAMAccountName
        bindDN: 'CN=Kalen Peterson,OU=Sirius,OU=OCPEval,DC=ocpeval,DC=scstec,DC=net'
        bindPassword:
          name: ldap-secret
        insecure: true
        url: >-
        # ldap://ldap.example.com:389/DC=ocpeval,DC=net?sAMAccountName?sub
        # ldaps://ldap.example.com:636/DC=ocpeval,DC=scstec,DC=net?sAMAccountName?sub
      mappingMethod: claim
      name: Active Directory
      type: LDAP
