kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: nutanix-files-dynamic
provisioner: csi.nutanix.com
parameters:
    dynamicProv: ENABLED
    nfsServerName: nfs01
    #nfsServerName above is File Server Name in Prism without DNS suffix, not the FQDN.
    csi.storage.k8s.io/provisioner-secret-name: ntnx-secret
    csi.storage.k8s.io/provisioner-secret-namespace: openshift-cluster-csi-drivers
storageType: NutanixFiles